--- 
files: 
  - 
    destination: /var/www/html/
    source: /index.hml
hooks: 
  AfterInstall: 
    - 
      location: scripts/start.sh
      owner: root
      timeout: 300
  BeforeInstall: 
    - 
      location: scripts/install_dependencies.sh
      owner: root
      timeout: 300
os: linux
permissions: 
  - 
    group: root
    mode: 777
    object: /var/www/html
    owner: root
version: 0.0
