--- 
files: 
  - 
    destination: /var/www/html/
    source: /index.hml
hooks: 
  AfterInstall: 
    - 
      location: "scripts/sed -i -e 's/\\r$//' start.sh"
      runas: root
      timeout: 300
  BeforeInstall: 
    - 
      location: "scripts/sed -i -e 's/\\r$//' install_dependencies.sh"
      runas: root
      timeout: 300
os: linux
permissions: 
  - 
    group: root
    mode: 777
    object: /var/www/html
    owner: root
version: 0.0
