--- 
files: 
  destination: /var/www/html
  source: /index.html
hooks: 
  BeforeInstall: 
    loaction: scripts/install_dependecies
    location: scripts/start_server
    runas: root
    timeout: 300
os: linux
version: 0.0
