--- 
files: 
  ? "-source"
  : "/index.html destination /var/www/html"
hooks: 
  BeforeInstall: 
    ? "-loaction"
    : "scripts/install_dependecies timeout 300 runas root"
    ? "-location"
    : "scripts/start_server timeout 300 runas root"
os: linux
version: 0.0
